sudo: required

services:
  - docker

before_install:
  - docker build -t bereketdeb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bereketdeb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-657022513498"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$Access_Key_ID"
  secret_access_key: "$Secret_access_key"
  